### ISSUE TITLE
Kubernetes port name generations are invalid

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/module-ballerina-c2c#183]
**Description:**
Building services with '/' in the base path will generate invalid port names in the k8s service.
```

import ballerina/http;
service / on new http:Listener(9090) {

    resource function get greeting() returns string {
        return "Hello, World!";
    }
}
```

```
spec:
  ports:
  - name: "svc-1--svc"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
