### ISSUE TITLE
Compiler fails to take default values when certain fields are missing

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#45]
**Description:**
$Subject.

**Steps to Reproduce**
Create Kubernetes.toml with following value and observe the generated k8s file.
```toml
[cloud.deployment.probes.readiness]
port=9091
path="/readyz"

[cloud.deployment.probes.liveness]
port=9091
path="/healthz"
```
