### ISSUE TITLE
Cannot run a Ballerina container as a non-root user

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/module-ballerina-c2c#504]
**Description:**
I tried a very simple Ballerina main function in a K8s cluster. I tried this sample for the sake of demonstration for this issue, but my actual use case has an HTTP2 client.

When we try the following code in K8s with Ballerina generated artefacts, it works without an issue.
```ballerina
import ballerina/io;

public function main() {
    io:println("Hello, World!");
}
```
However, I want to try this sample as a non-root user. So, I added the following configuration into the generated K8s YAML.

```yaml
      containers:
      - image: "ballerina/sample-main:v0.1.1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
```

Then, I couldn't deploy the K8s deployment. It returns the following error.

```sh
➜  ~ kubectl get pods
NAME                                         READY   STATUS                       RESTARTS        AGE
http-ssl-servic-deployment-c45fbff8f-9j9qq   1/1     Running                      1 (2d18h ago)   3d
k8s-sample-deployment-84c6947c8d-q8lqr       0/1     CreateContainerConfigError   0               6m7s

➜  ~ kubectl describe pod k8s-sample-deployment-84c6947c8d-q8lqr
Name:         k8s-sample-deployment-84c6947c8d-q8lqr
Namespace:    default
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m14s                  default-scheduler  Successfully assigned default/k8s-sample-deployment-84c6947c8d-q8lqr to lima-rancher-desktop
  Warning  Failed     4m9s (x12 over 6m14s)  kubelet            Error: container has runAsNonRoot and image has non-numeric user (ballerina), cannot verify user is non-root (pod: "k8s-sample-deployment-84c6947c8d-q8lqr_default(a996f3a6-1cf6-4241-9781-d3924fd0d0a9)", container: k8s-sample-deployment)
  Normal   Pulled     64s (x26 over 6m14s)   kubelet            Container image "ballerina/sample-main:v0.1.1" already present on machine
```

**Steps to reproduce:**
Try to build K8s artefacts using the abovementioned sample, and deploy it in a K8s cluster.

**Affected Versions:**
Ballerina 2201.0.1 (Swan Lake)

**OS, DB, other environment details and versions:**
- macOS
- Rancher version: 1.0.1
