### ISSUE TITLE
BAL_CONFIG_FILES value isnt appended multiple [[cloud.config.files]] entries

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#649]
**Description:**
$Subject.

```yaml
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config1.toml:"
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
