### ISSUE TITLE
Remove automatic SSL retrieval from the code

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#782]
**Description:**
$Subject.
This might lead to accidental dev certs existing in the generated code. As there's no way to disable this feature, its better to make this explicit. 

Solution - 
Add an entry to the Cloud.toml file

```toml
[[cloud.secret.files]]
file="resource."
mount_dir="./resource"
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
