### ISSUE TITLE
[Bug]: Generated k8s artifacts do not support logging configurations via Config.toml

### ISSUE THREAD

**Issue by chathurace** [ballerina-platform/module-ballerina-c2c#800]
### Description

I developed a ballerina package with a Config.toml to output logs in the json format. But when I create k8s artifacts for this (using bal build --cloud=k8s), the deployed pods in k8s do not log using the json format. I guess we are not copying the Config.toml to the working directory when creating k8s artifacts.

### Related area

-> CICD

**Comment by anuruddhal** [comment]
This is by design. Users must explicitly specify the `Config.toml` file to be copied into the `Cloud.toml` file. 
Refer the sample https://github.com/ballerina-platform/module-ballerina-c2c/tree/master/examples/kubernetes-mount-config-map-volumes

```toml
[[cloud.config.files]]
file="./data/Config.toml" # Path of the external file
name="sample5-config-map"
```
