### ISSUE TITLE
K8s Autoscaling enabled flag not working

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerina-c2c#86]
**Description:**
$Subject.

```toml
[cloud.deployment.autoscaling]
enable=false
```

This should stop generating HPA k8s artifacts.
